--Money Clicker

local Event:RemoteEvent = game:GetService("ReplicatedStorage").Events.ClickMoney
Event:FireServer()

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.EnterCode
Event:FireServer(
    "Code"
)
